# Generated by Django 4.1.13 on 2024-07-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
