# Generated by Django 5.0.6 on 2024-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='happy_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='upload/happy_customers')),
                ('position', models.CharField(max_length=10)),
                ('information', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
