# Generated by Django 5.0.6 on 2024-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_employee_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('profile', models.ImageField(upload_to='upload/Blogs')),
                ('summary', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
