# Generated by Django 4.1.13 on 2024-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='upload/Events')),
            ],
        ),
    ]
