# Generated by Django 5.0.6 on 2024-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_happy_customers_alter_number_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(),
        ),
    ]
