# Generated by Django 4.1.13 on 2024-07-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
        ),
    ]
