# Generated by Django 5.0.6 on 2024-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_blog_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='upload/Events')),
                ('About', models.CharField(max_length=200)),
                ('Link', models.URLField(blank=True, max_length=150, unique=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
