# Generated by Django 5.0.6 on 2024-06-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_number_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='cause',
        ),
    ]
