# Generated by Django 4.1.13 on 2024-07-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_multiple_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple',
            name='event',
        ),
        migrations.AddField(
            model_name='multiple',
            name='causes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cause'),
        ),
    ]
