# Generated by Django 5.0.6 on 2024-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_blog_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='summary',
            field=models.CharField(max_length=5000),
        ),
    ]
