# Generated by Django 5.0.6 on 2024-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cause_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('post', models.FileField(upload_to='upload/Volunteer_form')),
                ('comment', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cause',
            name='profile',
            field=models.ImageField(upload_to='upload/cause'),
        ),
    ]
